name: Check

on:
  push:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check code format
        run: ./gradlew spotlessCheck
