name: Lint

on:
  push:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-jdk-gradle

      - name: Lint
        run: ./gradlew lintDebug
